spring.application.name=spring-la-mia-pizzeria-crud
#data source
spring.datasource.url=jdbc:mysql://localhost:3306/pizzeria_db
spring.datasource.username=root
spring.datasource.password=Maks199818

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
